-- ============================================================
-- Import: Construction Companies — Stockport & surrounds (55 enriched records)
-- Run once in the Supabase SQL editor. Dedupes by company name.
-- Dissolved companies are imported with status = 'lost' and a note.
-- ============================================================

insert into organizations
  (name, company_number, status, sector, sic_code, town, county, postcode,
   address_line1, incorporated_on, ch_status, website, phone,
   enriched_at, enriched_by, enrichment)
select
  x.name, nullif(x.company_number,''), x.status::company_status,
  x.sector, x.sic_code, x.town, x.county, x.postcode,
  x.address_line1, x.incorporated_on, x.ch_status, x.website, x.phone,
  now(), 'prospect_research', x.enrichment
from jsonb_to_recordset($j$[
{"name":"Hallas & Co","company_number":"07699971","status":"prospect","sector":"Chartered Surveyors","sic_code":"74902 (Quantity surveying activities)","town":"London","county":null,"postcode":"TW2","address_line1":"32 Gould Road, Twickenham, TW2","incorporated_on":"2011-06-28","ch_status":"Active","website":"https://www.hallasandco.co.uk","phone":"02089489553","enrichment":{"source":"Construction (Stockport)","primary_contact":"Jon Hallas","email":"info@hallasandco.co.uk","directors":"Jon Hallas (Founder/MD); Christopher Irata (director)","facebook":"https://www.facebook.com/hallasandco","linkedin":"https://uk.linkedin.com/company/hallas-&-co-","ch_url":"https://find-and-update.company-information.service.gov.uk/company/07699971","confidence":"High","notes":"London surveyor not Stockport; phone matches. FB page not fully verified"}},
{"name":"Lee Adams Builders","company_number":"04691712","status":"prospect","sector":"Building Contractors","sic_code":null,"town":"Disley","county":null,"postcode":"SK14 1ND","address_line1":"48 Union Street, Hyde, England, SK14 1ND","incorporated_on":"2003-03-10","ch_status":"Active","website":"https://www.leeadamsbuilders.com","phone":"07831810680","enrichment":{"source":"Construction (Stockport)","primary_contact":"Lee Adams","email":"leeadamsbuilders@gmail.com","directors":"Lee Adams (proprietor/director)","facebook":"https://www.facebook.com/leeadamsbuilders/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/04691712","confidence":"High","notes":"Reg office Hyde; trades from Brooklands, Legh Rd, Disley SK12 2NF"}},
{"name":"Whitehall Builders Ltd","company_number":"06694531","status":"prospect","sector":"Building Contractors","sic_code":"41100 (Development of building projects)","town":"High Lane","county":"Stockport","postcode":"SK7 4RF","address_line1":"320 London Road, Hazel Grove, Stockport, England, SK7 4RF","incorporated_on":"2008-09-10","ch_status":"Active","website":"https://www.whitehallbuilders.co.uk","phone":"07710434425","enrichment":{"source":"Construction (Stockport)","primary_contact":"Paul Whitehall","email":"info@whitehallbuilders.co.uk","directors":"Paul Whitehall (director)","facebook":"https://www.facebook.com/WhitehallBuildersLtd/","instagram":"@whitehall_builders_ltd","ch_url":"https://find-and-update.company-information.service.gov.uk/company/06694531","confidence":"High","notes":"Reg office Hazel Grove; High Lane is trading address"}},
{"name":"JL Woodsmith","company_number":null,"status":"prospect","sector":"Carpenter","sic_code":null,"town":"High Lane","county":null,"postcode":null,"address_line1":"Unit 9, Lomber Hey Farm, Stockport area","incorporated_on":null,"ch_status":null,"website":"https://jlwoodsmith.com","phone":"07786073169","enrichment":{"source":"Construction (Stockport)","primary_contact":"Jordan","email":"jlwoodsmith@hotmail.com","directors":"Jordan (proprietor; likely sole trader)","facebook":"https://www.facebook.com/JLWoodsmith/","instagram":"@jlwoodsmith","confidence":"Medium","notes":"No CH match - likely sole trader. Owner first name Jordan only"}},
{"name":"All in Building Ltd","company_number":"14564368","status":"lost","sector":"Building Contractors","sic_code":"41100 (Development of building projects)","town":"Disley","county":"Cheshire","postcode":"SK12 2JU","address_line1":"4 Hilton Road, Disley, Stockport, Cheshire, SK12 2JU","incorporated_on":"2022-12-31","ch_status":"Dissolved","website":"https://allinbuildingltd.com","phone":"07557877458","enrichment":{"source":"Construction (Stockport)","directors":"NA","ch_url":"https://find-and-update.company-information.service.gov.uk/company/14564368","confidence":"Medium","notes":"DISSOLVED 4 Jun 2024 - no longer trading. Address+SIC match"}},
{"name":"Ashton Roofing & Building Construction Ltd","company_number":"09509623","status":"prospect","sector":"Roofing & Building","sic_code":null,"town":"Dukinfield","county":"Cheshire","postcode":"SK16 5DQ","address_line1":"24 Winchester Road, Dukinfield, Cheshire, England, SK16 5DQ","incorporated_on":"2015-03-25","ch_status":"Active","website":"https://www.ashtonroofing.co.uk","phone":"01613039100","enrichment":{"source":"Construction (Stockport)","primary_contact":"Ged Hurst","email":"info@ashtonroofing.co.uk","directors":"Ged Hurst (director)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/09509623","confidence":"High","notes":"Email inferred from domain - verify. Owner Ged Hurst per Which? Trusted Trader"}},
{"name":"Kay Construction","company_number":"07635872","status":"prospect","sector":"Building Contractors","sic_code":"43290 (Other construction installation)","town":"Marple","county":null,"postcode":"SK6 5AP","address_line1":"Green Meadows, 58 Townscliffe Lane, Marple Bridge, Stockport, SK6 5AP","incorporated_on":"2011-05-16","ch_status":"Active","website":"https://www.kayconstruction.co.uk","phone":"01614499767","enrichment":{"source":"Construction (Stockport)","primary_contact":"Ben Kay","email":"building@kayconstruction.co.uk","directors":"Philip Kay; Barbara Kay; Ben Kay (MD); Thomas Kay","facebook":"https://www.facebook.com/KayConstructionLtd/","instagram":"@kayconstruction","linkedin":"https://uk.linkedin.com/company/kay-construction-marple-ltd","ch_url":"https://find-and-update.company-information.service.gov.uk/company/07635872","confidence":"High","notes":"Ben Kay = MD (LinkedIn). Formerly Kay Homes Ltd"}},
{"name":"Cheadle Construction Company","company_number":null,"status":"prospect","sector":"Building Contractors","sic_code":null,"town":"Poynton","county":"Cheshire","postcode":"SK12 1TS","address_line1":"Wayford, Middlewood Road, Poynton, Cheshire, SK12 1TS","incorporated_on":null,"ch_status":null,"website":"https://www.cheadleconstruction.co.uk","phone":"07801415839","enrichment":{"source":"Construction (Stockport)","email":"info@cheadleconstructionconorthcheshire.co.uk","confidence":"Low","notes":"No CH entity confirmed - likely unincorporated. Seed email domain looks like a typo - verify"}},
{"name":"Marple Landscaping & Construction","company_number":null,"status":"prospect","sector":"Landscaping and Construction","sic_code":null,"town":"Marple","county":null,"postcode":"SK6 6DX","address_line1":"7 Heather Way, Marple, Stockport, SK6 6DX","incorporated_on":null,"ch_status":null,"website":null,"phone":"07832386684","enrichment":{"source":"Construction (Stockport)","primary_contact":"Gary","directors":"Gary (proprietor; likely sole trader)","facebook":"https://www.facebook.com/MarpleLandscapeAndConstruction/","confidence":"Medium","notes":"No CH match - likely sole trader. Owner Gary per reviews. No website"}},
{"name":"K.E. Hornby & Son Ltd","company_number":"05026712","status":"prospect","sector":"Building Contractors","sic_code":"41202 & 43999","town":"Hazel Grove","county":"Greater Manchester","postcode":"SK7 6JD","address_line1":"23 Rutland Road, Hazel Grove, Greater Manchester, SK7 6JD","incorporated_on":"2004-01-27","ch_status":"Active","website":"https://www.kehornby.co.uk","phone":"07718002232","enrichment":{"source":"Construction (Stockport)","primary_contact":"Kevin Hornby","email":"info@kehornby.co.uk","directors":"Kevin Hornby (director); Kyle Hornby (director); Sue Hornby (admin)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/05026712","confidence":"High","notes":"Family firm since 1901. Kevin & son Kyle run projects"}},
{"name":"North Cheshire Decorating","company_number":null,"status":"prospect","sector":"Decorating Service","sic_code":null,"town":"Poynton","county":"Greater Manchester","postcode":null,"address_line1":"Waterloo Rd, Poynton, Greater Manchester","incorporated_on":null,"ch_status":null,"website":"https://www.northcheshiredecorating.com","phone":"07565705612","enrichment":{"source":"Construction (Stockport)","email":"info@northcheshiredecorating.com","confidence":"Low","notes":"No CH match - likely sole trader. Alt landline 01625 879724 found"}},
{"name":"Low Cost Drives & Patios","company_number":null,"status":"prospect","sector":"Driveways","sic_code":null,"town":"Didsbury","county":null,"postcode":"M20 6UJ","address_line1":"Unit 73, 792 Wilmslow Rd, Manchester M20 6UJ","incorporated_on":null,"ch_status":null,"website":"https://www.lowcostdrivesandpatios.co.uk","phone":"0161 452 4912 / 07861 962 981","enrichment":{"source":"Construction (Stockport)","email":"sales.lowcostdrives@gmail.com","confidence":"Low","notes":"No CH entry under this name. gmail+mobile suggest sole trader/trading name"}},
{"name":"247 Plumber","company_number":"14732876","status":"prospect","sector":"Plumbing","sic_code":"43220 (plumbing, heat & air-con)","town":"Stockport","county":null,"postcode":"SK23 0HH","address_line1":"12 Market Street, Chapel-En-Le-Frith, High Peak, SK23 0HH","incorporated_on":"2023-03-15","ch_status":"Active","website":"https://www.247plumberstockport.co.uk","phone":"01614109247","enrichment":{"source":"Construction (Stockport)","directors":"1 director (name not captured)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/14732876","confidence":"Medium","notes":"Website serves Stockport/Hazel Grove; CH reg office Chapel-en-le-Frith. CH-to-website link inferred"}},
{"name":"Adobe Home Improvements (t/a Abode Roofing)","company_number":"14455976","status":"prospect","sector":"Roofing & Building","sic_code":"43910 (roofing activities)","town":"Manchester","county":null,"postcode":"BD1 3RG","address_line1":"46 Houghton Place, Bradford, BD1 3RG (changed Oct 2025)","incorporated_on":"2022-11-01","ch_status":"Active","website":"https://www.abode-roofing.co.uk/","phone":"07775504452","enrichment":{"source":"Construction (Stockport)","primary_contact":"Sam","email":"aboderoofing7@gmail.com","directors":"Sam (owner/director; surname not captured)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/14455976","confidence":"Medium","notes":"Seed Adobe is typo for Abode. Reg office Bradford/Cardiff not Manchester - verify entity"}},
{"name":"Pure H2O Exterior Cleaning","company_number":null,"status":"prospect","sector":"Pressure Washing","sic_code":null,"town":"Stockport","county":null,"postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":"https://pureh2oexteriorcleaning.uk","phone":"07833297459","enrichment":{"source":"Construction (Stockport)","primary_contact":"Phil","email":"pureh2oexterior-cleaning@gmail.com","directors":"Phil (owner; trading since 2013)","confidence":"Low","notes":"No CH match; gmail+sole-name suggest sole trader. Covers Stockport/Marple/Bramhall/Cheadle"}},
{"name":"Olive Tree Improvements","company_number":"12665816","status":"prospect","sector":"Landscaping and Construction","sic_code":"41100 (development of building projects)","town":"Stockport","county":null,"postcode":"SK12 1RH","address_line1":"179 Park Lane, Poynton, Stockport, SK12 1RH","incorporated_on":"2020-06-12","ch_status":"Active","website":"https://www.olivetreeimprovements.co.uk","phone":"07809743759","enrichment":{"source":"Construction (Stockport)","primary_contact":"Ross","email":"ross@olivetreeimprovements.co.uk","directors":"Ross (director)","facebook":"https://www.facebook.com/olivetreeimprovements/","instagram":"@olivetree_improvements","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12665816","confidence":"High","notes":"Email+phone match CH-registered firm"}},
{"name":"Glyn Smith","company_number":null,"status":"prospect","sector":"TV Aerials & Satellite Dishes","sic_code":null,"town":"High Lane","county":null,"postcode":"SK6","address_line1":"2 Alders Green Ave / 5 Fairacres Rd, High Lane SK6","incorporated_on":null,"ch_status":null,"website":null,"phone":"07974967220 / 01663 765037","enrichment":{"source":"Construction (Stockport)","primary_contact":"Glyn Smith","directors":"Glyn Smith (sole trader)","confidence":"Medium","notes":"Sole trader t/a Glyn Smith TV & Video Services. No CH entry"}},
{"name":"County Gates","company_number":"04518648","status":"prospect","sector":"Gate Installation","sic_code":"25110/25610/25990 (metal structures/coating/fabrication)","town":"Romiley","county":null,"postcode":"SK22 3EL","address_line1":"45 Union Road, High Peak, Derbyshire, SK22 3EL","incorporated_on":"2002-08-23","ch_status":"Active","website":"https://www.countygates.net","phone":"07469363991 / 0161 449 7607","enrichment":{"source":"Construction (Stockport)","primary_contact":"Lee Brinsley","email":"info@countygatesautoservice.co.uk","directors":"Lee Brinsley (Managing Director)","facebook":"https://www.facebook.com/countygates/","linkedin":"https://uk.linkedin.com/in/lee-brinsley-14708195","ch_url":"https://find-and-update.company-information.service.gov.uk/company/04518648","confidence":"Medium","notes":"Seed email domain differs from official sales@countygates.net - VERIFY. Works: Chadkirk Business Park, Romiley"}},
{"name":"The Stair Shop","company_number":"04777596","status":"prospect","sector":"Staircases","sic_code":"16290 (manufacture of other wood products)","town":"Reddish","county":null,"postcode":"SK4 1NU","address_line1":"Chamart House, Haigh Avenue, Stockport, SK4 1NU","incorporated_on":"2003-05-27","ch_status":"Active","website":"https://www.stairshop.co.uk","phone":"01614778077","enrichment":{"source":"Construction (Stockport)","primary_contact":"Mike Lomax","email":"office@stairshop.co.uk","directors":"Mike Lomax (MD); Sam Lomax","facebook":"https://www.facebook.com/TheStairShopLtd","ch_url":"https://find-and-update.company-information.service.gov.uk/company/04777596","confidence":"High","notes":"Founded 2000 by Paul & Mike Lomax; now run by Mike & Sam"}},
{"name":"Lakeside Tree Care","company_number":"13433293","status":"prospect","sector":"Tree Work","sic_code":"02400 (support services to forestry)","town":"Marple","county":"Stockport","postcode":"SK6 7HB","address_line1":"Old Hall Farm, Lakes Road, Marple, Stockport, SK6 7HB","incorporated_on":"2021-06-02","ch_status":"Active","website":"https://www.lakesidetreecare.co.uk","phone":"07725887630","enrichment":{"source":"Construction (Stockport)","primary_contact":"Nathan Sherratt","email":"nsherratt@lakesidetreecare.co.uk","directors":"Nathan Sherratt (PSC)","facebook":"https://www.facebook.com/marplestockporttreecare/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13433293","confidence":"High","notes":"Owner Nathan Sherratt (email prefix + PSC)"}},
{"name":"Saw Contracts","company_number":"07673054","status":"prospect","sector":"Home Improvement","sic_code":"43320 (joinery installation)","town":"Marple","county":null,"postcode":"M45 7PX","address_line1":"170 Park Lane, Whitefield, Manchester, M45 7PX","incorporated_on":"2011-06-16","ch_status":"Active","website":"https://www.sawcontractsltd.co.uk","phone":"07801490294","enrichment":{"source":"Construction (Stockport)","email":"sawcontracts@gmail.com","directors":"2 directors (Marple-based; names not captured)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/07673054","confidence":"High","notes":"Family firm, Marple directors (32 Cedar Road SK6 7QP). Reg office Whitefield"}},
{"name":"Nice & Tidy Landscaping & Garden Services","company_number":"12941545","status":"lost","sector":"Landscaping","sic_code":null,"town":"Manchester","county":null,"postcode":"M35 0AS","address_line1":"291 Oldham Road, Failsworth, Manchester, M35 0AS","incorporated_on":"2020-10-09","ch_status":"Dissolved","website":"https://www.niceandtidylandscaping.co.uk","phone":null,"enrichment":{"source":"Construction (Stockport)","email":"info@niceandtidylandscaping.co.uk","directors":"1 PSC","facebook":"https://www.facebook.com/niceandtidygardeningservices/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12941545","confidence":"Low","notes":"Linked CH co DISSOLVED 16 Apr 2024 but website live - current legal entity unclear"}},
{"name":"Solarus","company_number":"10560692","status":"prospect","sector":"Renewable Energy / Solar","sic_code":"43210 (Electrical installation)","town":"Bredbury","county":null,"postcode":"SK6 2SN","address_line1":"Unit 12 The Gate Centre, Bredbury Parkway, Stockport, SK6 2SN","incorporated_on":"2017-01-12","ch_status":"Active","website":"https://www.solarus.co.uk","phone":"01616740390","enrichment":{"source":"Construction (Stockport)","primary_contact":"Scott Coleman","email":"hello@solarus.co.uk","directors":"Scott Coleman (Director); Nathan James Hooley (Director)","facebook":"https://www.facebook.com/SolarusEnergy1/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/10560692","confidence":"High","notes":"Seed email typo hellow@ corrected to hello@. Company renamed over time, same office"}},
{"name":"Rob Preston","company_number":null,"status":"prospect","sector":"Plastering","sic_code":null,"town":"Stockport","county":null,"postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":"https://www.robprestonplasterer.co.uk","phone":"07967311818","enrichment":{"source":"Construction (Stockport)","primary_contact":"Rob Preston","email":"robprestonplasterer@gmail.com","directors":"Rob Preston (sole trader)","confidence":"High","notes":"Sole trader, no Ltd at CH. Seed data confirmed via website"}},
{"name":"Evergreen Landscaping Ltd","company_number":"05662740","status":"prospect","sector":"Landscaping","sic_code":"81300 (Landscape service activities)","town":"Stockport","county":null,"postcode":"SK4 1SU","address_line1":"23 Norris Towers, Wilkinson Rd, Stockport, SK4 1SU","incorporated_on":"2005-12-23","ch_status":"Active","website":"https://www.landscape-gardeners-stockport.co.uk","phone":"07791833143","enrichment":{"source":"Construction (Stockport)","primary_contact":"David Mark Andrew","email":"annekershaw600@aol.com","directors":"David Mark Andrew (Director); Ann Kershaw (Secretary)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/05662740","confidence":"High","notes":"Secretary Ann Kershaw matches seed email. Confirmation statement overdue. Trading addr Marple Bridge"}},
{"name":"North Cheshire Forestry Services","company_number":"08176924","status":"prospect","sector":"Tree Work","sic_code":"81300 (Landscape service activities)","town":"Marple","county":"Cheshire","postcode":"SK6 7EN","address_line1":"235 Windlehurst Road, Marple, Stockport, SK6 7EN","incorporated_on":"2012-08-13","ch_status":"Active","website":"https://www.northcheshireforestry.com","phone":"01614275813","enrichment":{"source":"Construction (Stockport)","primary_contact":"Christopher Alexander Whyatt","email":"info@northcheshireforestry.com","directors":"Christopher Alexander Whyatt (Director); Jennifer Louise Whyatt (Director)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/08176924","confidence":"High","notes":"Est 1976. FB referenced on Yell but URL unconfirmed"}},
{"name":"Birchvale Construction","company_number":"06008864","status":"prospect","sector":"Building Contractors","sic_code":"43390 (Other building completion)","town":"Romiley","county":null,"postcode":"SK4 2HD","address_line1":"c/o Hallidays, Riverside House, Kings Reach Business Park, Yew Street, Stockport, SK4 2HD","incorporated_on":"2006-11-24","ch_status":"Active - proposal to strike off","website":"https://www.birchvaleconstruction.co.uk","phone":"07792667407","enrichment":{"source":"Construction (Stockport)","primary_contact":"Jonathan Ralph Cross","email":"birchvaleconstruction@gmail.com","directors":"Jonathan Ralph Cross (Director)","linkedin":"https://www.linkedin.com/in/jonathan-cross-91712b20/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/06008864","confidence":"Medium","notes":"WARNING: active proposal to strike off; accounts overdue. LinkedIn is director personal profile"}},
{"name":"Geestar Glass Ltd","company_number":"11357642","status":"prospect","sector":"Windows & Doors","sic_code":"43342 (Glazing)","town":"Manchester","county":"Greater Manchester","postcode":"M18 7JL","address_line1":"106-108 Reddish Lane, Manchester, M18 7JL","incorporated_on":"2018-05-11","ch_status":"Active","website":null,"phone":"07854274459","enrichment":{"source":"Construction (Stockport)","primary_contact":"Mark Gee","email":"geestarwindows@gmail.com","directors":"Mark Gee (Director); Angela Emma Woolley (Director)","facebook":"https://www.facebook.com/p/GEEstar-Glass-100063706592104/","instagram":"@geestarglass","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11357642","confidence":"High","notes":"No website found. Email from FB/directory. Based Gee Cross/Hyde area"}},
{"name":"Steve James Landscape Gardener","company_number":null,"status":"prospect","sector":"Landscaping","sic_code":null,"town":"Romiley","county":null,"postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":"https://www.stevejameslandscaping.co.uk","phone":"07857450997","enrichment":{"source":"Construction (Stockport)","primary_contact":"Steve James","directors":"Steve James (sole trader)","confidence":"Medium","notes":"Sole trader, no Ltd at CH. Est 1998. Email not published online"}},
{"name":"MTEC Scaffolding Ltd","company_number":null,"status":"prospect","sector":"Scaffolding","sic_code":null,"town":null,"county":"Greater Manchester","postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":null,"phone":null,"enrichment":{"source":"Construction (Stockport)","confidence":"Low","notes":"No Greater Manchester CH match. Similar-named cos are London/Winchester - not confirmed"}},
{"name":"BSPS Ltd","company_number":null,"status":"prospect","sector":"Building Contractors","sic_code":null,"town":null,"county":null,"postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":"https://www.bspsltd.co.uk","phone":null,"enrichment":{"source":"Construction (Stockport)","confidence":"Low","notes":"BSPS Limited (05951655) registered London - location mismatch, not confirmed. Name generic"}},
{"name":"New Build Contractors Residential Specialists","company_number":null,"status":"prospect","sector":"Building Contractors","sic_code":null,"town":null,"county":null,"postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":null,"phone":null,"enrichment":{"source":"Construction (Stockport)","confidence":"Low","notes":"Name appears descriptive, not a registered entity. No local match confirmed"}},
{"name":"E&S Building Contractors","company_number":null,"status":"prospect","sector":"Building Contractors","sic_code":null,"town":null,"county":null,"postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":"http://escontractors.co.uk","phone":null,"enrichment":{"source":"Construction (Stockport)","confidence":"Low","notes":"E&S Building Contractors Ltd (12509578) is London N9 - cannot confirm same entity"}},
{"name":"JK Construction Ltd","company_number":null,"status":"prospect","sector":"Building Contractors","sic_code":null,"town":null,"county":null,"postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":null,"phone":null,"enrichment":{"source":"Construction (Stockport)","confidence":"Low","notes":"Name too generic; multiple JK Construction entities on CH, none confirmed local. Needs a location/contact to disambiguate"}},
{"name":"Projekt 7 Construction","company_number":"12498857","status":"prospect","sector":"Building Contractors","sic_code":null,"town":"London","county":null,"postcode":"SW1Y 4EX","address_line1":"30 Haymarket, 6th Floor, London, SW1Y 4EX","incorporated_on":"2020-03-04","ch_status":"Active","website":"https://projekt7.london/","phone":null,"enrichment":{"source":"Construction (Stockport)","ch_registered_name":"PROJEKT 7 CONSTRUCTION LIMITED","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12498857","confidence":"Low","notes":"CH name matches but company is London-based - likely wrong region for this lead. Verify"}},
{"name":"H&S Building Contractors","company_number":"11274127","status":"prospect","sector":"Building Contractors","sic_code":"41201, 41100","town":"Marple","county":"Stockport","postcode":"SK6 6DE","address_line1":"28a Church Lane, Marple, Stockport, SK6 6DE","incorporated_on":"2018-03-26","ch_status":"Active","website":null,"phone":null,"enrichment":{"source":"Construction (Stockport)","ch_registered_name":"H&S BUILDERS LIMITED","directors":"2 directors (corr. High Lane House, 148 Buxton Road)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11274127","confidence":"Medium","notes":"Name differs (CH Builders vs seed Building Contractors); best Stockport match - verify"}},
{"name":"RightBuilderCo","company_number":null,"status":"prospect","sector":"Building Contractors","sic_code":null,"town":null,"county":null,"postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":"https://www.rightbuilder.co.uk","phone":"07563774777","enrichment":{"source":"Construction (Stockport)","confidence":"Low","notes":"No CH match for rightbuilder.co.uk; mobile-only suggests sole trader/trading name"}},
{"name":"GMC Home Solutions","company_number":"10208335","status":"prospect","sector":"Building Contractors","sic_code":"43290 (other construction installation)","town":"Hazel Grove","county":null,"postcode":"SK7 3HA","address_line1":"62 Abingdon Road, Bramhall, Stockport, SK7 3HA","incorporated_on":"2016-06-01","ch_status":"Active","website":"https://www.gmchomesolutions.co.uk","phone":"07989470234","enrichment":{"source":"Construction (Stockport)","primary_contact":"Michael Thomas","email":"gmchomesolutions@gmail.com","directors":"Michael Thomas (director)","facebook":"https://www.facebook.com/gmchomesolutions/","instagram":"@gmcsolutionsltd","ch_url":"https://find-and-update.company-information.service.gov.uk/company/10208335","confidence":"High","notes":"Trading addr Newby Road Ind Est Hazel Grove. IG handle may be a related GMC Solutions - verify"}},
{"name":"RASEN Building Services","company_number":"11289371","status":"prospect","sector":"Building Contractors","sic_code":"41100 (development of building projects)","town":"Bredbury","county":null,"postcode":"SK6 2BR","address_line1":"Unit 12, Crosland Industrial Estate, Stockport Road West, Bredbury, SK6 2BR","incorporated_on":"2018-04-04","ch_status":"Active","website":"https://www.rasenbs-ltd.co.uk","phone":"01613991412","enrichment":{"source":"Construction (Stockport)","primary_contact":"Blazej Jerzy Czarczyk","email":"info@rasen-bs.co.uk","directors":"Blazej Jerzy Czarczyk (director)","facebook":"https://www.facebook.com/Rasen.b.s/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11289371","confidence":"High","notes":"Corr addr 29 Oxford Drive, Woodley SK6 1HU"}},
{"name":"Stockport Construction","company_number":"07568226","status":"prospect","sector":"Building Contractors","sic_code":null,"town":"Stockport","county":null,"postcode":"SK23 7LY","address_line1":"Unit 11 Bingswood Trading Estate, Whaley Bridge, High Peak, SK23 7LY","incorporated_on":"2011-03-17","ch_status":"Active","website":"https://www.stockportconstruction.com","phone":"01615630920","enrichment":{"source":"Construction (Stockport)","primary_contact":"G Johnson","email":"info@stockportconstruction.co.uk","directors":"G Johnson (director) + secretary","facebook":"https://www.facebook.com/stockportconstructionltd/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/07568226","confidence":"High","notes":"Carpentry/joinery/building. Corr. 56 Fox Street, Edgeley SK3 9JY"}},
{"name":"Prima Construction","company_number":"13816522","status":"prospect","sector":"Building Contractors","sic_code":"41202 (construction of domestic buildings)","town":"Cheadle","county":null,"postcode":"SK8 1DR","address_line1":"31 Wilmslow Road, Cheadle, SK8 1DR","incorporated_on":"2021-12-23","ch_status":"Active","website":"https://www.primaconstructionltd.co.uk","phone":"01617061777","enrichment":{"source":"Construction (Stockport)","primary_contact":"Joe Hewitt","email":"joe@primaconstruction.co.uk","directors":"Joe Hewitt (director)","facebook":"https://www.facebook.com/primaconstructionltd/","instagram":"@primaconstructionltd","linkedin":"https://www.linkedin.com/in/joe-hewitt-b104992b7","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13816522","confidence":"High","notes":"Joe Hewitt confirmed via LinkedIn + CH. FMB member"}},
{"name":"Lauderdale Builders","company_number":null,"status":"prospect","sector":"Building Contractors","sic_code":null,"town":"Offerton","county":null,"postcode":"SK2 5SX","address_line1":"1 Garth Road, Stockport, SK2 5SX","incorporated_on":null,"ch_status":null,"website":"https://www.sitelift.site/lauderdalebuilders","phone":"07850755370","enrichment":{"source":"Construction (Stockport)","email":"lauderdalebuilders@gmail.com","directors":"Family-run (3 generations; owner name not published)","confidence":"Low","notes":"Likely sole trader/partnership - no CH record. On Checkatrade & Stockport council approved list"}},
{"name":"Manifest Construction","company_number":"11265885","status":"prospect","sector":"Building Contractors","sic_code":null,"town":"Chadkirk","county":"Stockport","postcode":"SK12 1LT","address_line1":"4 Dombey Road, Poynton, Stockport, SK12 1LT","incorporated_on":"2018-03-20","ch_status":"Active","website":"https://www.manifestconstruction.co.uk","phone":"07881226151","enrichment":{"source":"Construction (Stockport)","primary_contact":"Adam Robert Shingleton","email":"info@manifestconstruction.co.uk","directors":"Adam Robert Shingleton (director)","facebook":"https://www.facebook.com/ManifestConstruction18/","linkedin":"https://uk.linkedin.com/in/adam-shingleton-6bb63b278","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11265885","confidence":"High","notes":"Trades from Chadkirk Ind Est Romiley. NOT Manifest In Construction 15668958"}},
{"name":"KJL Builders","company_number":"11939291","status":"prospect","sector":"Building Contractors","sic_code":"41201, 41202","town":"Hazel Grove","county":null,"postcode":"M28 1DT","address_line1":"24 Berwick Close, Worsley, Manchester, M28 1DT","incorporated_on":"2019-04-11","ch_status":"Active","website":"https://www.kjlbuilders.co.uk","phone":"07549997985","enrichment":{"source":"Construction (Stockport)","email":"kjlbuilders@gmail.com","directors":"Active director (name not captured)","facebook":"https://www.facebook.com/kjlbuilder/","instagram":"@kjlbuilders","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11939291","confidence":"Medium","notes":"Reg office Worsley but website/socials serve Hazel Grove/Stockport - confirm same operator"}},
{"name":"Rightio Plumbing & Heating","company_number":"12523871","status":"prospect","sector":"Plumbing","sic_code":"81100 (combined facilities support)","town":"Hazel Grove","county":null,"postcode":"B68 0NP","address_line1":"210 Trigate, 210-222 Hagley Road West, Oldbury, Birmingham, B68 0NP","incorporated_on":"2020-03-18","ch_status":"Active","website":"https://www.rightio.co.uk","phone":"01612667893","enrichment":{"source":"Construction (Stockport)","primary_contact":"Karl Tulloch","directors":"Karl Tulloch (founder) +1","ch_registered_name":"RIGHTIO SUBCONTRACTOR LIMITED","linkedin":"https://www.linkedin.com/company/rightio","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12523871","confidence":"Medium","notes":"National brand HQ Birmingham. Stockport phone is local routing. Also Rightio Ltd 07357774 (in liquidation)"}},
{"name":"Prescott & Joule","company_number":"09246526","status":"prospect","sector":"Kitchens & Bedrooms","sic_code":"47599 (retail furniture/lighting)","town":"Great Moor","county":"Stockport","postcode":"SK2 7NR","address_line1":"265-267 Buxton Road, Stockport, SK2 7NR","incorporated_on":"2014-10-02","ch_status":"Active","website":"https://www.prescottandjoule.com","phone":"01614840850","enrichment":{"source":"Construction (Stockport)","primary_contact":"Helen Joule","email":"enquiries@prescottandjoule.com","directors":"Helen Joule (designer/owner); Leon (designer)","ch_registered_name":"PRESCOTT & JOULE KITCHENS LTD","facebook":"https://www.facebook.com/prescottandjoulekitchens/","instagram":"@prescottandjoulekitchens","linkedin":"https://uk.linkedin.com/in/helen-joule-83454a177","ch_url":"https://find-and-update.company-information.service.gov.uk/company/09246526","confidence":"High","notes":"SEED TRADE WRONG: bespoke kitchens/bedrooms, not estate agents. Sister co = Creative Design & Build"}},
{"name":"Lucinda Barnes & Sons Roofing","company_number":null,"status":"prospect","sector":"Roofing & Building","sic_code":null,"town":"Marple","county":"Stockport","postcode":"SK6 7QL","address_line1":"43 Buxton Lane / 67 Upper Hibbert Ln, Marple SK6 7QL","incorporated_on":null,"ch_status":null,"website":"https://www.lucindabarnes-roofing.co.uk","phone":"07876388703","enrichment":{"source":"Construction (Stockport)","primary_contact":"Lucinda Barnes","email":"lucindajbarnes@gmail.com","directors":"Lucinda Barnes (t/a Abstract Roofing & Property Maintenance)","facebook":"https://www.facebook.com/abstractroofing/","confidence":"Medium","notes":"Likely sole trader/family business (25+ yrs), no Ltd found. FB = abstractroofing"}},
{"name":"More than Loft Ladders","company_number":null,"status":"prospect","sector":"Loft Ladders / Loft","sic_code":null,"town":null,"county":"Greater Manchester","postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":"https://www.morethanloftladders.co.uk","phone":"01617140423","enrichment":{"source":"Construction (Stockport)","primary_contact":"Paul Langley","directors":"Paul Langley (franchisee)","facebook":"https://www.facebook.com/MoreThanLoftLaddersNottingham/","linkedin":"https://uk.linkedin.com/in/paul-langley-8a2746b3","confidence":"Low","notes":"National franchise (HQ Nottingham). GM branch run by Paul Langley; his Ltd not confirmed (15702179 dissolved Jan-2025)"}},
{"name":"Mr Soot Chimney Sweep","company_number":"13580825","status":"prospect","sector":"Chimney Sweep","sic_code":"81221/81222 (chimney cleaning)","town":"Wigan","county":"Greater Manchester","postcode":"WN3 4DP","address_line1":"Unit 7 Tower Enterprise Park, Great George Street, Wigan, WN3 4DP","incorporated_on":"2021-08-23","ch_status":"Active","website":"https://mr-soot.com","phone":"01617061217","enrichment":{"source":"Construction (Stockport)","primary_contact":"David","directors":"David (founder/Master Sweep)","facebook":"https://www.facebook.com/mrsootchimneysweep/","instagram":"@mr_soot_sweep","linkedin":"https://uk.linkedin.com/company/mr-soot-chimney-sweep","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13580825","confidence":"High","notes":"HETAS approved. Also 0800 0541154 / 07724 311992. Director full name not captured"}},
{"name":"Poynton Roofing","company_number":null,"status":"prospect","sector":"Roofing & Building","sic_code":null,"town":"Poynton","county":"Cheshire","postcode":"SK10 5DY","address_line1":"15 East Ave, Bollington SK10 5DY","incorporated_on":null,"ch_status":null,"website":"https://www.poyntonroofing.co.uk","phone":"07792997535","enrichment":{"source":"Construction (Stockport)","primary_contact":"Gary","email":"poyntonroofing@gmail.com","directors":"Gary (per reviews; trading since 1999)","confidence":"Medium","notes":"Likely sole trader (since 1999), no Ltd found. Also 01625 572660. Seed phone had a stray extra digit - corrected"}},
{"name":"Queensgate Glass Ltd","company_number":null,"status":"prospect","sector":"Glass Splashbacks","sic_code":null,"town":"Bramhall","county":"Stockport","postcode":null,"address_line1":null,"incorporated_on":null,"ch_status":null,"website":"https://queensgateglass.co.uk","phone":"07715418795","enrichment":{"source":"Construction (Stockport)","email":"enquiries@queensgateglass.co.uk","instagram":"@queensgateglass","confidence":"Low","notes":"Trades as Ltd but no CH match surfaced - verify on CH directly. Splashbacks/mirrors, NOT windows. Also 0161 4390069"}},
{"name":"Cheadle Roof Repairs","company_number":"17127904","status":"prospect","sector":"Roofing & Building","sic_code":"43910 (roofing activities)","town":"Cheadle","county":null,"postcode":"OL16 2QD","address_line1":"41 Tarnside Close, Rochdale, OL16 2QD","incorporated_on":"2026-03-31","ch_status":"Active","website":"https://www.cheadleroofrepairs.co.uk","phone":"07398522771","enrichment":{"source":"Construction (Stockport)","email":"info@cheadleroofrepairs.co.uk","directors":"Director b. Aug 1998 (name not captured)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/17127904","confidence":"Medium","notes":"Newly incorporated 31-Mar-2026; reg office Rochdale not Cheadle. Site claims 25 years - verify"}},
{"name":"Creative Design & Build","company_number":"11643714","status":"prospect","sector":"Home Improvement / Building","sic_code":"41200/43999 (construction)","town":"Great Moor","county":"Stockport","postcode":"SK2 7NR","address_line1":"263 Buxton Road, Great Moor, Stockport, SK2 7NR","incorporated_on":"2018-10-25","ch_status":"Active","website":"https://www.cdbit.co.uk","phone":"01614840850","enrichment":{"source":"Construction (Stockport)","primary_contact":"Helen Joule","email":"creativedesignandbuild@aol.com","directors":"Helen Joule; Andy Murray (builder/joiner)","ch_registered_name":"CREATIVE DESIGN AND BUILD (CHESHIRE) LTD","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11643714","confidence":"High","notes":"CONFIRMED sister company of Prescott & Joule Kitchens (shared phone & adjacent address). FMB member"}},
{"name":"Jaxon Rose Makeovers","company_number":"12780464","status":"prospect","sector":"Home Improvement / Makeovers","sic_code":"43320 (joinery installation)","town":"Stockport","county":null,"postcode":"LE9 8BE","address_line1":"The Enterprise Centre, Dawsons Lane, Barwell, Leicester, LE9 8BE","incorporated_on":"2020-07-30","ch_status":"Active","website":"https://www.jaxonrosemakeovers.co.uk","phone":null,"enrichment":{"source":"Construction (Stockport)","ch_registered_name":"JAXON ROSE LIMITED","directors":"Director b. Apr 1980 (name not captured)","facebook":"https://www.facebook.com/jaxonrosestockport/","instagram":"@jaxonrose_makeovers","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12780464","confidence":"Low","notes":"Multi-entity group (Leics HQ). Showroom at Notcutts SK7 1QS. Confirm which entity invoices in Stockport"}},
{"name":"The Window Repair Centre","company_number":"05481160","status":"prospect","sector":"Windows & Doors","sic_code":null,"town":"Hazel Grove","county":"Stockport","postcode":"ST5 6AT","address_line1":"Unit 9 Watermills Road, Chesterton, Newcastle, Staffs, ST5 6AT","incorporated_on":"2005-06-15","ch_status":"Active","website":"https://www.windowrepaircentre.com","phone":"01614010415","enrichment":{"source":"Construction (Stockport)","primary_contact":"Martin Hancock","ch_registered_name":"WINDOW REPAIR CENTRE LIMITED","directors":"Martin Hancock (contact/principal)","facebook":"https://www.facebook.com/thewindowrepaircentre/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/05481160","confidence":"Medium","notes":"Stockport branch 215-217 London Rd, Hazel Grove; reg office in Staffs. Which? Trusted Trader"}}
]$j$::jsonb) as x(
  name text, company_number text, status text, sector text, sic_code text,
  town text, county text, postcode text, address_line1 text,
  incorporated_on date, ch_status text, website text, phone text, enrichment jsonb
)
where not exists (select 1 from organizations o where o.name = x.name);

-- primary contacts (only where a name was captured)
insert into contacts (org_id, full_name, email, is_primary, source)
select o.id, o.enrichment->>'primary_contact', nullif(o.enrichment->>'email',''), true, 'prospect_research'
from organizations o
where o.enriched_by = 'prospect_research'
  and o.enrichment->>'source' = 'Construction (Stockport)'
  and coalesce(o.enrichment->>'primary_contact','') <> ''
  and not exists (select 1 from contacts c where c.org_id = o.id);

-- tag the batch
insert into tags (label) values ('Prospect') on conflict do nothing;
insert into taggables (tag_id, entity_type, entity_id)
select t.id, 'organization', o.id
from organizations o cross join tags t
where o.enriched_by = 'prospect_research'
  and o.enrichment->>'source' = 'Construction (Stockport)'
  and t.label = 'Prospect'
on conflict do nothing;
