-- ============================================================
-- Import: North West Prospects (51 enriched records)
-- Run once in the Supabase SQL editor. Dedupes by company name.
-- Socials / directors / notes / confidence are stored in organizations.enrichment (jsonb).
-- A primary contact is created wherever a real name was captured.
-- ============================================================

insert into organizations
  (name, company_number, status, sector, sic_code, town, county, postcode,
   address_line1, incorporated_on, ch_status, website, phone,
   enriched_at, enriched_by, enrichment)
select
  x.name, nullif(x.company_number,''), 'prospect'::company_status,
  x.sector, x.sic_code, x.town, x.county, x.postcode,
  x.address_line1, x.incorporated_on, x.ch_status, x.website, x.phone,
  now(), 'prospect_research', x.enrichment
from jsonb_to_recordset($j$[
{"name":"Outwood Electrical","company_number":"08619176","sector":"Electrician","sic_code":null,"town":"Bury","county":"Greater Manchester","postcode":"BL9 8PF","address_line1":"12 Alexander Drive, Bury, England, BL9 8PF","incorporated_on":"2013-07-22","ch_status":"Active","website":"https://www.outwoodelectricalltd.co.uk","phone":"07889 574594","enrichment":{"source":"North West Prospects","primary_contact":"Stuart Wall","email":"info@outwoodelectricalltd.co.uk","directors":"Stuart Wall (director/owner)","facebook":"https://www.facebook.com/OutwoodElectricalLtd/","linkedin":"https://uk.linkedin.com/company/outwood-electrical-limited","ch_url":"https://find-and-update.company-information.service.gov.uk/company/08619176","confidence":"High","notes":"Family-run, single director"}},
{"name":"A Mellor Plumbing & Heating","company_number":"08030981","sector":"Plumber/Heating","sic_code":null,"town":"Rochdale","county":"Greater Manchester","postcode":"OL11 2YW","address_line1":"Unit 6 Blue Pit Mill, Queensway, Rochdale, England, OL11 2YW","incorporated_on":"2012-04-16","ch_status":"Active","website":"https://amellorplumbingandheating.co.uk","phone":"01706 351006","enrichment":{"source":"North West Prospects","primary_contact":"Anthony Mellor","email":"info@amellorplumbingandheating.co.uk","directors":"Anthony Mellor (director)","facebook":"https://www.facebook.com/amph.co.uk/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/08030981","confidence":"High","notes":"Family firm. Site notes a Twitter but X handle not found"}},
{"name":"DMK Landscape & Design","company_number":"15751938","sector":"Landscaper/Garden services","sic_code":"81300 (Landscape service activities)","town":"Wigan","county":"Greater Manchester","postcode":"WN5 8BU","address_line1":"5 Wardley Street, Wigan, England, WN5 8BU","incorporated_on":"2024-05-31","ch_status":"Active","website":"https://dmklandscapeanddesign.co.uk","phone":null,"enrichment":{"source":"North West Prospects","primary_contact":"David Knell","directors":"David Knell (director/owner)","facebook":"https://www.facebook.com/p/DMK-Landscape-And-Design-LTD-61573037180784/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/15751938","confidence":"Medium","notes":"Phone/email on site contact page; not captured. New co (2024)"}},
{"name":"Hart Electrical Services Northwest","company_number":"14899663","sector":"Electrician","sic_code":"43210 (Electrical installation)","town":"Bury","county":"Greater Manchester","postcode":"M3 7BG","address_line1":"The Copper Room, Deva City Office Park, Trinity Way, Manchester, England, M3 7BG","incorporated_on":"2023-05-29","ch_status":"Active","website":"https://buryelectricians.co.uk","phone":"07802 679407","enrichment":{"source":"North West Prospects","primary_contact":"Luke Andrew Halsall-Hart","email":"info@hartelectrical.uk","directors":"Luke Andrew Halsall-Hart (director)","facebook":"https://www.facebook.com/p/Hart-Electrical-Services-Northwest-LTD-100093382434561/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/14899663","confidence":"High","notes":"Reg office is accountant's; trades in Bury"}},
{"name":"Oakwood Tree Services (Bolton)","company_number":"15672510","sector":"Tree surgeon","sic_code":null,"town":"Westhoughton","county":"Greater Manchester","postcode":"BL1 4BY","address_line1":"Carlyle House, 78 Chorley New Road, Bolton, England, BL1 4BY","incorporated_on":"2024-04-23","ch_status":"Active","website":"https://oakwoodtrees.co.uk","phone":"01942 812115","enrichment":{"source":"North West Prospects","primary_contact":"Shaun","directors":"Shaun (owner; named on site)","facebook":"https://www.facebook.com/OakwoodTreeServicesBolton/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/15672510","confidence":"Medium","notes":"Alt 07873 721712; email not found; director full name unconfirmed"}},
{"name":"Altrincham Decorating","company_number":"09662237","sector":"Painter/Decorator","sic_code":null,"town":"Timperley","county":"Greater Manchester","postcode":"WA15 7DB","address_line1":"32 Briarfield Road, Timperley, Altrincham, England, WA15 7DB","incorporated_on":"2015-06-29","ch_status":"Active","website":"https://altrinchamdecorators.co.uk","phone":"0161 570 0342","enrichment":{"source":"North West Prospects","directors":"Director (painter; name unconfirmed)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/09662237","confidence":"Medium","notes":"Website/trading name vs CH name link likely; verify. No socials found"}},
{"name":"LGH Plumbing & Heating Services","company_number":"09896583","sector":"Plumber/Heating","sic_code":null,"town":"Leigh","county":"Greater Manchester","postcode":"M46 9DL","address_line1":"C/O Atherton Accountancy Ltd, 30 Bolton Old Road, Atherton, Manchester, England, M46 9DL","incorporated_on":"2015-12-01","ch_status":"Active","website":"https://www.lghltd.com","phone":"01942 896381","enrichment":{"source":"North West Prospects","directors":"2 directors (names unconfirmed)","facebook":"https://www.facebook.com/lghltd","ch_url":"https://find-and-update.company-information.service.gov.uk/company/09896583","confidence":"High","notes":"Reg office is accountant's; trades from Kenyon Court, Leigh WN7 3PT"}},
{"name":"Trafford Bathrooms","company_number":"10013208","sector":"Bathroom fitter/Renovation","sic_code":"43390 (Other building completion and finishing)","town":"Sale","county":"Greater Manchester","postcode":"M33 2RU","address_line1":"30 Rostherne Road, Sale, M33 2RU","incorporated_on":"2016-02-18","ch_status":"Active","website":"https://traffordbathrooms.co.uk","phone":null,"enrichment":{"source":"North West Prospects","primary_contact":"Brendan Patrick Fogarty","directors":"Brendan Patrick Fogarty (director, 100% owner)","facebook":"https://www.facebook.com/people/Trafford-Bathrooms-Ltd/100071626441308/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/10013208","confidence":"High","notes":"Phone/email on site contact page, not captured"}},
{"name":"Belvoir Contractors","company_number":"13212681","sector":"Driveways/Groundworks","sic_code":null,"town":"Bolton","county":"Greater Manchester","postcode":"BL1 3AJ","address_line1":"67 Chorley Old Road, Bolton, England, BL1 3AJ","incorporated_on":"2021-02-19","ch_status":"Active","website":"https://belvoircontractors.co.uk","phone":"07425 528812","enrichment":{"source":"North West Prospects","email":"info@belvoircontractors.co.uk","directors":"Director (name unconfirmed)","facebook":"https://www.facebook.com/belvoirgroundworks/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13212681","confidence":"High","notes":"Also 0800 368 5171. Family-run"}},
{"name":"GR Building Contractors","company_number":"09987677","sector":"Builder/Extensions","sic_code":null,"town":"Wigan","county":"Greater Manchester","postcode":"WN2 5HR","address_line1":"81 Stratton Drive, Platt Bridge, Wigan, England, WN2 5HR","incorporated_on":"2016-02-04","ch_status":"Active","website":"https://www.grbuilding.uk","phone":"01942 867851","enrichment":{"source":"North West Prospects","primary_contact":"Gaz Royds","email":"info@grbuilding.co.uk","directors":"Gaz Royds (director/owner)","facebook":"https://www.facebook.com/GrBuildingContractors/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/09987677","confidence":"High","notes":"Also 07545 981443. Correspondence addr 86 Davy Rd"}},
{"name":"Your Local Roofers NW","company_number":"12973658","sector":"Roofer","sic_code":null,"town":"Little Lever","county":"Greater Manchester","postcode":"BL3 1TF","address_line1":"3 Carlisle Close, Little Lever, Bolton, England, BL3 1TF","incorporated_on":"2020-10-26","ch_status":"Active","website":"https://www.your-local-roofer.co.uk","phone":null,"enrichment":{"source":"North West Prospects","directors":"Director (name unconfirmed)","facebook":"https://www.facebook.com/YourLocalRoofer/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12973658","confidence":"Medium","notes":"NFRC member. Phone/email not captured; verify website"}},
{"name":"Premier Plastering & K Rendering","company_number":"14985546","sector":"Plasterer/Renderer","sic_code":null,"town":"Horwich","county":"Greater Manchester","postcode":"BL6 7AF","address_line1":"168 Lee Lane, Horwich, Bolton, Lancashire, England, BL6 7AF","incorporated_on":"2023-07-06","ch_status":"Active","website":"https://premierplastering.uk","phone":"07931 074601","enrichment":{"source":"North West Prospects","email":"sales@premierplastering.uk","directors":"2 directors (plasterers; names unconfirmed)","facebook":"https://www.facebook.com/p/Premier-Plastering-K-Rendering-100092598277237/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/14985546","confidence":"High","notes":"20+ yrs exp; covers Bolton/Wigan/Chorley/Manchester"}},
{"name":"Droylsden Glass","company_number":"07173979","sector":"Window/Door installer","sic_code":null,"town":"Audenshaw","county":"Greater Manchester","postcode":"M34 5HJ","address_line1":"42-56 Audenshaw Road, Audenshaw, Manchester, England, M34 5HJ","incorporated_on":"2010-03-02","ch_status":"Active","website":"https://www.droylsdenglass.co.uk","phone":"0161 292 1122","enrichment":{"source":"North West Prospects","email":"info@droylsdenglass.co.uk","directors":"Director (PSC; name unconfirmed)","linkedin":"https://uk.linkedin.com/company/droylsden-glass","ch_url":"https://find-and-update.company-information.service.gov.uk/company/07173979","confidence":"Medium","notes":"Est 1982 (incorporated 2010). FB not confirmed"}},
{"name":"Murray Building Contractors","company_number":"16472155","sector":"Builder/Roofing & Joinery","sic_code":"43320 (Joinery installation)","town":"Prestwich","county":"Greater Manchester","postcode":"M24 1RU","address_line1":"Suite 3 Turner Business Centre, Greengate, Middleton, Greater Manchester, England, M24 1RU","incorporated_on":"2025-05-23","ch_status":"Active","website":"https://www.murraybuildingcontractors.com","phone":null,"enrichment":{"source":"North West Prospects","primary_contact":"Murray","directors":"Murray (director/owner; full name unconfirmed)","facebook":"https://www.facebook.com/murraybuilding/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/16472155","confidence":"Medium","notes":"Very new co (May 2025); trading since 2023 per site"}},
{"name":"Cheshire Bespoke Building","company_number":"13598855","sector":"Builder","sic_code":null,"town":"Macclesfield","county":"Cheshire","postcode":"SK11 7RG","address_line1":"55 Maple Avenue, Macclesfield, Cheshire, SK11 7RG","incorporated_on":"2021-09-02","ch_status":"Active","website":"https://www.cheshirebespokebuilding.com/","phone":null,"enrichment":{"source":"North West Prospects","primary_contact":"Tomas","directors":"Tomas (owner)","facebook":"https://www.facebook.com/CheshireBespokeBuilding/","instagram":"@cheshirebespokebuildingltd","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13598855","confidence":"High","notes":"Family-run builder. Owner first name only; SIC/email/phone not confirmed"}},
{"name":"Niblett Construction","company_number":"14428864","sector":"Builder/Renovation","sic_code":null,"town":"Middlewich","county":"Cheshire","postcode":"CW10 0AD","address_line1":"32 Sutton Lane, Middlewich, Cheshire, CW10 0AD","incorporated_on":"2022-10-19","ch_status":"Active","website":"https://niblettconstruction.co.uk/","phone":"01606 832294 / 07368 298246","enrichment":{"source":"North West Prospects","email":"enquiries@niblettconstruction.co.uk","directors":"Niblett (director name not confirmed)","facebook":"https://www.facebook.com/p/Niblett-Construction-100083709639645/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/14428864","confidence":"High","notes":"FMB member. Director full name not confirmed"}},
{"name":"Sandbach Construction","company_number":"11114276","sector":"Builder/Roofing","sic_code":null,"town":"Sandbach","county":"Cheshire","postcode":"CW11 3HQ","address_line1":"17 Elworth Road, Sandbach, Cheshire, CW11 3HQ","incorporated_on":"2017-12-15","ch_status":"Active","website":"https://sandbachconstruction.co.uk/","phone":"01270 760689 / 07762 133578","enrichment":{"source":"North West Prospects","primary_contact":"Simon Merner","email":"info@sandbachconstruction.co.uk","directors":"Simon Merner","facebook":"https://www.facebook.com/sandbachconstruction/","instagram":"@sandbachconstruction","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11114276","confidence":"High","notes":"Building+roofing+driveways. Guild of Master Craftsmen"}},
{"name":"Keytech Developments","company_number":"12307831","sector":"Renovation/Home Improvement","sic_code":null,"town":"Congleton","county":"Cheshire","postcode":"CW12 1DY","address_line1":"Riverside Offices, Mountbatten Way, Congleton, Cheshire, CW12 1DY","incorporated_on":"2019-11-11","ch_status":"Active","website":"https://www.keytechdevelopmentsltd.co.uk/","phone":"07831 468869","enrichment":{"source":"North West Prospects","primary_contact":"Adam","email":"adam@keytechdevelopments.co.uk","directors":"Adam (owner/director)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12307831","confidence":"Medium","notes":"FMB/TrustMark. Owner first name only; no socials found"}},
{"name":"Cheshire Roof Repairs","company_number":"12393226","sector":"Roofer","sic_code":null,"town":"Knutsford","county":"Cheshire","postcode":"WA16 8HY","address_line1":"Parkview, Mobberley Road, Knutsford, Cheshire, WA16 8HY","incorporated_on":"2020-01-09","ch_status":"Active","website":"https://cheshireroofrepairs.co.uk/","phone":"01565 859698","enrichment":{"source":"North West Prospects","email":"admin@cheshireroofrepairs.co.uk","directors":"Director name not confirmed","facebook":"https://www.facebook.com/cheshireroofrepairs/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12393226","confidence":"High","notes":"CORC member. Director name not in snippets"}},
{"name":"JDR Landscapes","company_number":"13411647","sector":"Landscaper","sic_code":null,"town":"Crewe","county":"Cheshire","postcode":"CW2 6TP","address_line1":"16 Acorn Bank Close, Crewe, Cheshire, CW2 6TP","incorporated_on":"2021-05-20","ch_status":"Active","website":null,"phone":"07413 678577","enrichment":{"source":"North West Prospects","directors":"2 directors (names not confirmed)","facebook":"https://www.facebook.com/JDRlandscapesltd/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13411647","confidence":"Medium","notes":"Landscaping & construction. No website/email; director names not in snippets"}},
{"name":"K S Whittaker Plastering","company_number":"06843095","sector":"Plasterer/Renderer","sic_code":null,"town":"Macclesfield","county":"Cheshire","postcode":"SK10 1QS","address_line1":"12 Ecton Avenue, Macclesfield, SK10 1QS","incorporated_on":"2009-03-11","ch_status":"Active","website":"https://kswplastering.co.uk/","phone":"01625 869961","enrichment":{"source":"North West Prospects","primary_contact":"Scott Whittaker","directors":"Scott Whittaker","facebook":"https://www.facebook.com/kswplastering/","instagram":"@kswplastering","ch_url":"https://find-and-update.company-information.service.gov.uk/company/06843095","confidence":"High","notes":"Established plasterer/renderer. Email not found"}},
{"name":"Ben Turner Electrical","company_number":"12076704","sector":"Electrician","sic_code":null,"town":"Frodsham","county":"Cheshire","postcode":"WA6 7HS","address_line1":"25 Coronation Drive, Frodsham, WA6 7HS","incorporated_on":"2019-07-01","ch_status":"Active","website":"https://www.benturnerelectrical.co.uk/","phone":null,"enrichment":{"source":"North West Prospects","primary_contact":"Ben Turner","directors":"Ben Turner","facebook":"https://www.facebook.com/BenTurnerElectrical/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12076704","confidence":"High","notes":"Family-run since 2012. Phone/email not fully captured"}},
{"name":"Scott James Plumbing and Heating","company_number":"09637302","sector":"Plumber/Heating","sic_code":null,"town":"Wrenbury","county":"Cheshire","postcode":"CW5 8HF","address_line1":"Springfield, New Road, Wrenbury, Cheshire, CW5 8HF","incorporated_on":"2015-06-12","ch_status":"Active","website":"https://www.scottjamesplumbingandheating.co.uk/","phone":"07809 133173","enrichment":{"source":"North West Prospects","primary_contact":"Scott Heirene","email":"info@scottjamesplumbingandheating.co.uk","directors":"Scott Heirene","ch_url":"https://find-and-update.company-information.service.gov.uk/company/09637302","confidence":"High","notes":"Gas Safe/Oftec family firm. No socials found"}},
{"name":"Mark J Wilson Plumbing and Renewables","company_number":"13843844","sector":"Plumber/Renewables","sic_code":"43220 (plumbing/heat/air-con)","town":"Crewe","county":"Cheshire","postcode":"CW1 6EA","address_line1":"7-9 Macon Court, Crewe, Cheshire, CW1 6EA","incorporated_on":"2022-01-12","ch_status":"Active","website":"https://mjwplumbingandrenewables.co.uk/","phone":null,"enrichment":{"source":"North West Prospects","primary_contact":"Mark James Wilson","directors":"Mark James Wilson; Amy McGill Murphy","facebook":"https://www.facebook.com/p/MJW-Plumbing-and-Renewables-Ltd-61584553185355/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13843844","confidence":"High","notes":"Trades as MJW Plumbing & Renewables"}},
{"name":"Cheshire Tree Surgeons","company_number":"05358622","sector":"Tree Surgeon","sic_code":null,"town":"Frodsham","county":"Cheshire","postcode":"WA6 8PD","address_line1":"The Old Market Garden, Moss Lane, Norley, Frodsham, WA6 8PD","incorporated_on":"2005-02-09","ch_status":"Active","website":"https://www.cheshiretreesurgeons.co.uk/","phone":"01565 621234","enrichment":{"source":"North West Prospects","email":"info@cheshiretreesurgeons.co.uk","directors":"Director name not confirmed","ch_url":"https://find-and-update.company-information.service.gov.uk/company/05358622","confidence":"Medium","notes":"Trades as Craftwoods & Cheshire Tree Surgeons. No socials/director name found"}},
{"name":"BK Scaffolding Congleton","company_number":"12937806","sector":"Scaffolder","sic_code":"43999 (scaffold erection)","town":"Congleton","county":"Cheshire","postcode":"CW12 4TR","address_line1":"2 The Courtyard, Greenfield Farm Industrial Estate, Congleton, CW12 4TR","incorporated_on":"2020-10-08","ch_status":"Active","website":"https://bk-scaffolding.business.site/","phone":null,"enrichment":{"source":"North West Prospects","directors":"Director name not confirmed","facebook":"https://www.facebook.com/bkscaffolding/","instagram":"@bkscaffoldingltd","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12937806","confidence":"Medium","notes":"CHAS/SMAS accredited. Google business site only; director/phone not in snippets"}},
{"name":"Cestrian Glazing Repairs","company_number":"11607146","sector":"Window/Door Installer","sic_code":null,"town":"Ellesmere Port","county":"Cheshire","postcode":"CH65 4EH","address_line1":"Unit 37, Canal Bridge Enterprise Centre, Meadow Lane, Ellesmere Port, CH65 4EH","incorporated_on":"2018-09-19","ch_status":"Active","website":"https://www.cestrianglazingchester.co.uk/","phone":"0151 355 4816","enrichment":{"source":"North West Prospects","primary_contact":"Damian Hudson","email":"cestrianglazingchester@gmail.com","directors":"Damian Hudson; James Hudson","facebook":"https://www.facebook.com/cestrianglazing/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11607146","confidence":"High","notes":"Father/son family firm. Shares site/FB with Cestrian Glazing & Conservatories"}},
{"name":"Natural Landscaping","company_number":"13333203","sector":"Landscaping/paving","sic_code":null,"town":"Chorley","county":"Lancashire","postcode":"PR7 2FG","address_line1":"23 Nab Wood Drive, Chorley, England, PR7 2FG","incorporated_on":"2021-04-14","ch_status":"Active","website":"https://natural-landscaping.co.uk","phone":"07450 094758","enrichment":{"source":"North West Prospects","primary_contact":"Mark","directors":"2 directors (contact Mark)","facebook":"https://www.facebook.com/NaturalLandscapingLtd/","instagram":"@natural_landscapingltd","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13333203","confidence":"High","notes":"Socials active. SIC not seen in snippets"}},
{"name":"Bedrock Landscapes","company_number":"06149929","sector":"Landscaping/garden","sic_code":null,"town":"Clayton-le-Woods","county":"Lancashire","postcode":"PR6 7JD","address_line1":"473 Preston Road, Clayton Le Woods, Chorley, PR6 7JD","incorporated_on":"2007-03-09","ch_status":"Active","website":"https://www.bedrocklandscapesltd.co.uk","phone":null,"enrichment":{"source":"North West Prospects","directors":"2 directors + secretary","facebook":"https://www.facebook.com/hartwoodlandscapes/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/06149929","confidence":"Medium","notes":"FB link uncertain (hartwood result); verify. 3 officers - check still owner-active"}},
{"name":"Trunks Tree Care","company_number":"11629783","sector":"Tree surgeon","sic_code":null,"town":"Leyland","county":"Lancashire","postcode":"PR26 6RA","address_line1":"Lodge House, Lodge Lane, Farington Moss, Leyland, PR26 6RA","incorporated_on":"2018-10-18","ch_status":"Active","website":"https://www.trunkstreecare.co.uk","phone":"01772 914842","enrichment":{"source":"North West Prospects","directors":"2 directors","facebook":"https://www.facebook.com/Trunkstreecare/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11629783","confidence":"High","notes":"Family-run. Email via web form only"}},
{"name":"Lingard & Lomax Joinery","company_number":"09892603","sector":"Joinery/carpentry","sic_code":"43320 (Joinery installation)","town":"Blackburn","county":"Lancashire","postcode":"BB2 5LQ","address_line1":"5 Geddes Street, Blackburn, Lancashire, BB2 5LQ","incorporated_on":"2015-11-27","ch_status":"Active","website":"https://www.lingardlomaxjoinery.co.uk","phone":"07939 677780","enrichment":{"source":"North West Prospects","primary_contact":"Warren Lomax","directors":"Warren Lomax (joiner) + secretary","facebook":"https://www.facebook.com/lingardandlomax/","linkedin":"https://uk.linkedin.com/company/lingard-lomax-joinery","ch_url":"https://find-and-update.company-information.service.gov.uk/company/09892603","confidence":"High","notes":"Owner-managed. Trades address 100 Kings Road BB2 4PY"}},
{"name":"Roofix Roofing and Building Contractors","company_number":"12425096","sector":"Roofer","sic_code":null,"town":"Burnley","county":"Lancashire","postcode":"BB10 1PD","address_line1":"Northbridge House, Elm Street, Burnley, BB10 1PD","incorporated_on":"2020-01-27","ch_status":"Active","website":"https://www.roofixuk.com","phone":"01282 216635","enrichment":{"source":"North West Prospects","primary_contact":"David Malcolm Burley","email":"info@roofixuk.com","directors":"David Malcolm Burley; Mark Alan Heys","facebook":"https://www.facebook.com/RoofixBurnley/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12425096","confidence":"High","notes":"2 directors. Contact via website"}},
{"name":"Lancashire Roofing & Building","company_number":"12905560","sector":"Roofer/builder","sic_code":"43390, 43910","town":"Lancaster","county":"Lancashire","postcode":"LA1 1WD","address_line1":"Dalton House, 9 Dalton Square, Lancaster, LA1 1WD","incorporated_on":"2020-09-25","ch_status":"Active","website":"https://www.lancashireroofingandbuilding.com","phone":"07927 279106","enrichment":{"source":"North West Prospects","primary_contact":"George","email":"info@lancashireroofingandbuilding.com","directors":"2 directors (MD George)","facebook":"https://www.facebook.com/LancashireRoofingAndBuildingLtd/","instagram":"@lancashireroofingandbuilding","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12905560","confidence":"Medium","notes":"Lancaster reg office but website/FB show Accrington base - possible name overlap, verify"}},
{"name":"Taylor's Scaffolding","company_number":"11173376","sector":"Scaffolder","sic_code":null,"town":"Accrington","county":"Lancashire","postcode":"BB5 5EL","address_line1":"123 Kingsway, Accrington, Lancashire, BB5 5EL","incorporated_on":"2018-01-29","ch_status":"Active","website":"https://taylorsscaffoldingltd.co.uk","phone":null,"enrichment":{"source":"North West Prospects","email":"taylorsscaffolding@gmail.com","directors":"Taylor family director(s)","facebook":"https://www.facebook.com/TAYLORSSCAFFOLDING/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11173376","confidence":"High","notes":"Local Accrington firm. Phone not found in snippets"}},
{"name":"JPC Decor","company_number":"05723916","sector":"Painter/decorator","sic_code":null,"town":"Lytham St Annes","county":"Lancashire","postcode":"FY8 1PQ","address_line1":"Bromley House, 2 Bromley Road, Lytham St. Annes, FY8 1PQ","incorporated_on":"2006-02-28","ch_status":"Active","website":"https://www.jpcdecor.co.uk","phone":null,"enrichment":{"source":"North West Prospects","directors":"Director (painter)","facebook":"https://www.facebook.com/jpcdecor/","linkedin":"https://uk.linkedin.com/company/jpc-decor-limited-lytham-st-annes","ch_url":"https://find-and-update.company-information.service.gov.uk/company/05723916","confidence":"High","notes":"Family-run single director. Phone/email via site"}},
{"name":"Paul J Lambert Plumbing & Heating","company_number":"08737897","sector":"Plumber/heating","sic_code":null,"town":"Leyland","county":"Lancashire","postcode":"PR25 4UD","address_line1":"61 Stanifield Lane, Farington, Leyland, PR25 4UD","incorporated_on":"2013-10-17","ch_status":"Active","website":null,"phone":"01772 455880","enrichment":{"source":"North West Prospects","primary_contact":"Paul J Lambert","directors":"Paul J Lambert (sole director)","facebook":"https://www.facebook.com/paullambertplumbingandheating/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/08737897","confidence":"High","notes":"Single director-owner. No website - FB only"}},
{"name":"Blackburn Gas Plumbing & Heating","company_number":"08636516","sector":"Plumber/gas/heating","sic_code":"43220 (Plumbing/heat/air-con)","town":"Blackburn","county":"Lancashire","postcode":"BB1 1TR","address_line1":"243 Pringle Street, Blackburn, Lancashire, BB1 1TR","incorporated_on":"2013-08-05","ch_status":"Active","website":"https://blackburngas.co.uk","phone":null,"enrichment":{"source":"North West Prospects","directors":"Director + secretary","facebook":"https://www.facebook.com/blackburn.gas/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/08636516","confidence":"High","notes":"Owner-managed Gas Safe firm"}},
{"name":"All Seasons Paving","company_number":"06583397","sector":"Driveways/paving","sic_code":null,"town":"Morecambe","county":"Lancashire","postcode":"LA3 3PA","address_line1":"39 Northgate, White Lund Industrial Estate, Morecambe, LA3 3PA","incorporated_on":"2008-05-02","ch_status":"Active","website":"https://allseasonspaving.co.uk","phone":null,"enrichment":{"source":"North West Prospects","directors":"1 director (family firm)","facebook":"https://www.facebook.com/allseasonspaving/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/06583397","confidence":"High","notes":"Family firm covering Preston/Chorley/Lancaster. Email/phone via site"}},
{"name":"CGS (Glazing)","company_number":"04925354","sector":"Window/door installer","sic_code":null,"town":"Burnley","county":"Lancashire","postcode":"BB12 0RW","address_line1":"Hollins Barn, Ightenhill Park Lane, Burnley, BB12 0RW","incorporated_on":"2003-10-08","ch_status":"Active","website":"https://cgsglazing.co.uk","phone":"01200 469038","enrichment":{"source":"North West Prospects","directors":"Director(s) - small family firm","ch_url":"https://find-and-update.company-information.service.gov.uk/company/04925354","confidence":"Medium","notes":"FENSA-reg uPVC installer. Phone is Clitheroe line; FB not confirmed"}},
{"name":"M-Tech Electrical Contractors","company_number":"07073891","sector":"Electrician","sic_code":"43210 (Electrical installation)","town":"Bootle","county":"Merseyside","postcode":"L3 4BN","address_line1":"Office 1 Brunswick House, Brunswick Way, Liverpool, Merseyside, L3 4BN","incorporated_on":"2009-11-12","ch_status":"Active","website":"http://www.m-techelec.co.uk","phone":null,"enrichment":{"source":"North West Prospects","primary_contact":"James Michael Winters","directors":"James Michael Winters; Eric Winters","facebook":"https://www.facebook.com/MTechElecrical/","linkedin":"https://www.linkedin.com/company/m-techelec","ch_url":"https://find-and-update.company-information.service.gov.uk/company/07073891","confidence":"High","notes":"Trading addr 75 Strand Rd, Bootle L20 4BB. No email/phone in snippets"}},
{"name":"Lumbers Northwest","company_number":"13853465","sector":"Tree surgery","sic_code":null,"town":"Wallasey","county":"Merseyside","postcode":"CH44 3EH","address_line1":"10 Burford Avenue, Wallasey, England, CH44 3EH","incorporated_on":"2022-01-17","ch_status":"Active","website":"https://lumbersnorthwest.co.uk","phone":"07711865770","enrichment":{"source":"North West Prospects","email":"info@lumberstreecare.uk","directors":"Single director (family-run)","facebook":"https://www.facebook.com/lumbersnorthwestltd/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13853465","confidence":"High","notes":"Director name not in snippets. Trades as Lumbers Tree & Hedge Care"}},
{"name":"St Helens Windows","company_number":"05439759","sector":"Windows/doors installer","sic_code":null,"town":"St Helens","county":"Merseyside","postcode":"WA9 3AS","address_line1":"Unit 1a, Jackson Street, St Helens, Merseyside, WA9 3AS","incorporated_on":"2005-04-29","ch_status":"Active","website":"https://sthelenswindows.com","phone":"01744 611203","enrichment":{"source":"North West Prospects","primary_contact":"Gary Stephen Burgess","email":"sales@sthelenswindows.com","directors":"Gary Stephen Burgess (MD)","facebook":"https://www.facebook.com/sthelenswindowsltd/","instagram":"@sthelenswindows","ch_url":"https://find-and-update.company-information.service.gov.uk/company/05439759","confidence":"High","notes":"Family-owned 30+ yrs. Sole active director"}},
{"name":"JS Construction Wirral","company_number":"12540254","sector":"Builder/bricklayer","sic_code":null,"town":"Wallasey","county":"Merseyside","postcode":"CH45 8PR","address_line1":"15 Somerset Road, Wallasey, CH45 8PR","incorporated_on":"2020-03-31","ch_status":"Active","website":"https://www.jsconstructionwirral.co.uk/","phone":"07794 702650","enrichment":{"source":"North West Prospects","primary_contact":"James","email":"jsconstructionwirral@yahoo.co.uk","directors":"Single director James (75%+ PSC)","facebook":"https://www.facebook.com/JSconstructionwirral/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12540254","confidence":"High","notes":"Single director-owner, time-served bricklayer. No Instagram found"}},
{"name":"Abbey Landscapes","company_number":"05308740","sector":"Landscaper/garden services","sic_code":"43999 (Other specialised construction)","town":"Southport","county":"Merseyside","postcode":"PR9 0PG","address_line1":"55 Hoghton Street, Southport, Merseyside, PR9 0PG","incorporated_on":"2004-12-09","ch_status":"Active","website":"https://www.rhinolandscapes.co.uk/","phone":null,"enrichment":{"source":"North West Prospects","directors":"2 directors","ch_registered_name":"ABBEY LANDSCAPES (FORMBY) LIMITED","facebook":"https://www.facebook.com/AbbeyLandscapesFormby/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/05308740","confidence":"Medium","notes":"Website mapping uncertain (Rhino Landscapes / Abbey assoc.); verify site+email"}},
{"name":"Plastercore","company_number":"10573932","sector":"Plasterer/damp proofer","sic_code":null,"town":"Wallasey","county":"Merseyside","postcode":"CH44 5SY","address_line1":"20 Surrey Street, Wallasey, CH44 5SY","incorporated_on":"2017-01-20","ch_status":"Active","website":"https://www.plastercore.co.uk/","phone":"07834 404265","enrichment":{"source":"North West Prospects","primary_contact":"Michael","email":"plastercore@gmail.com","directors":"Single director Michael","facebook":"https://www.facebook.com/plastercore/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/10573932","confidence":"High","notes":"Owner-operated by Michael, 20+ yrs. Which? Trusted Trader"}},
{"name":"Prescot Plumbing & Heating","company_number":"11055214","sector":"Plumber/heating","sic_code":null,"town":"Prescot","county":"Merseyside","postcode":"L34 6HS","address_line1":"36-38 St. Helens Road, Prescot, England, L34 6HS","incorporated_on":"2017-11-09","ch_status":"Active","website":"https://prescotplumbingheating.co.uk/","phone":null,"enrichment":{"source":"North West Prospects","directors":"Director(s) not named","facebook":"https://www.facebook.com/PrescotPlumbingheating/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/11055214","confidence":"High","notes":"Director name not seen. Trading 25+ yrs under new mgmt"}},
{"name":"DG Construction Wirral","company_number":"13000488","sector":"Builder/home improvement","sic_code":null,"town":"Heswall","county":"Merseyside","postcode":"CH64 9XF","address_line1":"5 Parkgate Road, Neston, Cheshire, CH64 9XF","incorporated_on":"2020-11-05","ch_status":"Active","website":"https://www.dgconstructionwirral.co.uk/","phone":"07547 947420","enrichment":{"source":"North West Prospects","primary_contact":"Daniel Grant","email":"dgrantconstruction1@gmail.com","directors":"Daniel Grant (founder/director)","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13000488","confidence":"Medium","notes":"FMB member; single owner Daniel Grant. RO Neston (Cheshire border) - serves Wirral. No socials found"}},
{"name":"Heaven on Earth Landscapes","company_number":"04244767","sector":"Landscaper/garden design","sic_code":"96090 (Other service activities)","town":"Woolton","county":"Merseyside","postcode":"L3 4BJ","address_line1":"c/o Stuart McBain Ltd, Unit 14 Tower Street, Brunswick Business Park, Liverpool, L3 4BJ","incorporated_on":"2001-07-02","ch_status":"Active","website":"https://www.heavenonearthlandscapes.uk/","phone":null,"enrichment":{"source":"North West Prospects","directors":"Director + secretary","facebook":"https://www.facebook.com/heavenonearthlandscapes.uk/","linkedin":"https://www.linkedin.com/company/heaven-on-earth-landscaping","ch_url":"https://find-and-update.company-information.service.gov.uk/company/04244767","confidence":"Medium","notes":"RO is accountant's address; business based Woolton L25. No email/phone in snippets"}},
{"name":"Bladerunners Landscapes","company_number":"05991178","sector":"Landscaper/garden services","sic_code":null,"town":"Southport","county":"Merseyside","postcode":"PR8 4JR","address_line1":"24 Clifford Road, Southport, Merseyside, PR8 4JR","incorporated_on":"2006-11-07","ch_status":"Active","website":"https://www.bladerunnerslandscapes.co.uk/","phone":null,"enrichment":{"source":"North West Prospects","primary_contact":"David","directors":"Director David + secretary","ch_url":"https://find-and-update.company-information.service.gov.uk/company/05991178","confidence":"Medium","notes":"Family-run 20+ yrs. Socials/email/phone not in snippets"}},
{"name":"Wareing & McKenna Roofing","company_number":"12776331","sector":"Roofer","sic_code":"43910 (Roofing activities)","town":"Wallasey","county":"Merseyside","postcode":"L3 9QJ","address_line1":"Suites C-F 14th Floor The Plaza, Old Hall Street, Liverpool, L3 9QJ","incorporated_on":"2020-07-29","ch_status":"Active","website":"https://wareingmckenna.co.uk/","phone":"07397 538781","enrichment":{"source":"North West Prospects","primary_contact":"Paul","email":"info@wareingmckenna.co.uk","directors":"Director Paul (family-run)","facebook":"https://www.facebook.com/wareingmckenna/","ch_url":"https://find-and-update.company-information.service.gov.uk/company/12776331","confidence":"High","notes":"Family-run, trading addr Unit 1 BMB Ind Pk, Docks Link, Wallasey CH44 3EQ. RO serviced-office"}},
{"name":"Tall Scaffolding Liverpool","company_number":"13365240","sector":"Scaffolder","sic_code":null,"town":"Mossley Hill","county":"Merseyside","postcode":"L18 1DG","address_line1":"48-52 Penny Lane, Mossley Hill, Liverpool, Merseyside, L18 1DG","incorporated_on":"2021-04-29","ch_status":"Active","website":null,"phone":"0151 203 4009","enrichment":{"source":"North West Prospects","directors":"Director(s) not named","ch_url":"https://find-and-update.company-information.service.gov.uk/company/13365240","confidence":"Low","notes":"No website/socials found; phone via directory. Verify it is micro/owner-managed before outreach"}}
]$j$::jsonb) as x(
  name text, company_number text, sector text, sic_code text,
  town text, county text, postcode text, address_line1 text,
  incorporated_on date, ch_status text, website text, phone text, enrichment jsonb
)
where not exists (select 1 from organizations o where o.name = x.name);

-- primary contacts (only where a name was captured)
insert into contacts (org_id, full_name, email, is_primary, source)
select o.id, o.enrichment->>'primary_contact', nullif(o.enrichment->>'email',''), true, 'prospect_research'
from organizations o
where o.enriched_by = 'prospect_research'
  and o.enrichment->>'source' = 'North West Prospects'
  and coalesce(o.enrichment->>'primary_contact','') <> ''
  and not exists (select 1 from contacts c where c.org_id = o.id);

-- tag the batch
insert into tags (label) values ('Prospect') on conflict do nothing;
insert into taggables (tag_id, entity_type, entity_id)
select t.id, 'organization', o.id
from organizations o cross join tags t
where o.enriched_by = 'prospect_research'
  and o.enrichment->>'source' = 'North West Prospects'
  and t.label = 'Prospect'
on conflict do nothing;
