-- ============================================================
-- 0003_seed.sql
-- Demo/seed data has been intentionally REMOVED.
-- This project runs on real data only — do not add demo inserts here.
-- (Historical demo seed was deleted from the database on 16 Jun 2026.)
-- ============================================================
